import { readdirSync, writeFileSync, readFileSync, mkdirSync, existsSync } from "node:fs";
import { join, relative, dirname, resolve, basename } from "node:path";
import { createHash } from "node:crypto";
import type { Plugin, ViteDevServer } from "vite";
import { DirEntry, ResolvedDir, StaticAssetsOptions } from "./types";
import { normalizeDirs } from "./utils";



export default function staticAssets(options: StaticAssetsOptions = {}): Plugin {
    const {
        dirs = ["public"],
        outDir = "src/generated",
        extensions = [],
        exclude = [],
        fnName = "asset",
        typeName = "AssetPath",
    } = options;

    let resolvedDirs: ResolvedDir[] = [];

    // ─── Core logic ──────────────────────────────────────────

    function shouldInclude(filePath: string): boolean {
        if (exclude.some((pattern) => filePath.includes(pattern))) return false;
        if (extensions.length > 0) return extensions.some((ext) => filePath.endsWith(ext));
        return true;
    }

    function collectPaths(dir: string, rootDir: string, prefix: string): string[] {
        if (!existsSync(dir)) return [];

        const paths: string[] = [];
        const entries = readdirSync(dir, { withFileTypes: true })
            .filter((e: { name: string }) => !e.name.startsWith("."))
            .sort((a: { name: string }, b: { name: string }) => a.name.localeCompare(b.name));

        for (const entry of entries) {
            const fullPath = join(dir, entry.name);
            const relPath = prefix + "/" + relative(rootDir, fullPath).replace(/\\/g, "/");

            if (entry.isDirectory()) {
                paths.push(...collectPaths(fullPath, rootDir, prefix));
            } else if (shouldInclude(relPath)) {
                paths.push(relPath);
            }
        }

        return paths.sort();
    }

    function generateModule(paths: string[], dirLabel: string): string {
        const pathUnion =
            paths.length > 0
                ? paths.map((p) => `  | ${JSON.stringify(p)}`).join("\n")
                : '  | (string & { __brand: "empty" })';

        return [
            `// ──────────────────────────────────────────────────────`,
            `// AUTO-GENERATED by vite-plugin-static-assets`,
            `// Source directory: ${dirLabel}`,
            `// Do not edit manually — changes will be overwritten.`,
            `// ──────────────────────────────────────────────────────`,
            ``,
            `/**`,
            ` * Union of every valid static asset path from "${dirLabel}".`,
            ` * Compile-time only — adds zero bytes to the production bundle.`,
            ` */`,
            `export type ${typeName} =`,
            `${pathUnion};`,
            ``,
            `/**`,
            ` * Validate and return a static asset path.`,
            ` *`,
            ` * Identity function at runtime — any bundler will inline it`,
            ` * to a bare string literal. Zero overhead.`,
            ` *`,
            ` * @example`,
            ` *   const src = ${fnName}("/images/hero.png");          // ✅ autocomplete + validated`,
            ` *   const bad = ${fnName}("/images/missing.png");       // ❌ TypeScript error`,
            ` */`,
            `export function ${fnName}<T extends ${typeName}>(path: T): T {`,
            `  return path;`,
            `}`,
            ``,
        ].join("\n");
    }

    function writeIfChanged(entry: ResolvedDir, content: string): boolean {
        const hash = createHash("md5").update(content).digest("hex");
        if (hash === entry.lastHash) return false;

        mkdirSync(dirname(entry.outFile), { recursive: true });
        writeFileSync(entry.outFile, content, "utf-8");
        entry.lastHash = hash;
        return true;
    }

    function generateForDir(entry: ResolvedDir): boolean {
        const paths = collectPaths(entry.absPath, entry.absPath, entry.prefix);
        const content = generateModule(paths, entry.relPath);
        return writeIfChanged(entry, content);
    }

    function generateAll(): string[] {
        const changed: string[] = [];

        for (const entry of resolvedDirs) {
            if (generateForDir(entry)) {
                changed.push(entry.outRelative);
            }
        }

        return changed;
    }

    // ─── Vite plugin hooks ───────────────────────────────────

    return {
        name: "vite-plugin-typesafe-assets",
        enforce: "pre",

        configResolved(config) {
            const root = config.root;
            resolvedDirs = normalizeDirs(dirs, root, outDir);

            // Pre-load existing file hashes to avoid unnecessary writes
            for (const entry of resolvedDirs) {
                if (existsSync(entry.outFile)) {
                    const existing = readFileSync(entry.outFile, "utf-8");
                    entry.lastHash = createHash("md5").update(existing).digest("hex");
                }
            }
        },

        buildStart() {
            const changed = generateAll();
            if (changed.length > 0) {
                console.log(`[static-assets] Generated: ${changed.join(", ")}`);
            }
        },

        configureServer(server: ViteDevServer) {
            const watcher = server.watcher;

            const handleChange = (filePath: string) => {
                const normalizedPath = resolve(filePath);

                const entry = resolvedDirs.find((d) =>
                    normalizedPath.startsWith(d.absPath),
                );

                if (!entry) return;

                const changed = generateForDir(entry);
                if (changed) {
                    const relFile = relative(entry.absPath, normalizedPath);
                    console.log(
                        `[static-assets] Regenerated ${entry.outRelative} (${relFile} changed)`,
                    );
                }
            };

            for (const entry of resolvedDirs) {
                watcher.add(entry.absPath);
            }

            watcher.on("add", handleChange);
            watcher.on("unlink", handleChange);
            watcher.on("unlinkDir", handleChange);
        },
    };
}

