import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { normalizeDirs } from "./normalize";
import type {
    GeneratorRuntimeOptions,
    ResolvedDir,
    StaticAssetsGenerator,
    StaticAssetsOptions,
} from "./types";

function shouldInclude(
    filePath: string,
    extensions: string[],
    exclude: string[],
): boolean {
    if (exclude.some((pattern) => filePath.includes(pattern))) return false;
    if (extensions.length > 0) return extensions.some((ext) => filePath.endsWith(ext));
    return true;
}

function collectPaths(
    dir: string,
    rootDir: string,
    prefix: string,
    extensions: string[],
    exclude: string[],
): string[] {
    if (!existsSync(dir)) return [];

    const paths: string[] = [];
    const entries = readdirSync(dir, { withFileTypes: true })
        .filter((entry) => !entry.name.startsWith("."))
        .sort((a, b) => a.name.localeCompare(b.name));

    for (const entry of entries) {
        const fullPath = join(dir, entry.name);
        const relPath = `${prefix}/${relative(rootDir, fullPath).replace(/\\/g, "/")}`;

        if (entry.isDirectory()) {
            paths.push(...collectPaths(fullPath, rootDir, prefix, extensions, exclude));
        } else if (shouldInclude(relPath, extensions, exclude)) {
            paths.push(relPath);
        }
    }

    return paths.sort();
}

function generateModule(paths: string[], dirLabel: string, typeName: string, fnName: string): string {
    const pathUnion =
        paths.length > 0
            ? paths.map((p) => `  | ${JSON.stringify(p)}`).join("\n")
            : '  | (string & { __brand: "empty" })';

    return [
        "// ──────────────────────────────────────────────────────",
        "// AUTO-GENERATED by typesafe-assets",
        `// Source directory: ${dirLabel}`,
        "// Do not edit manually - changes will be overwritten.",
        "// ──────────────────────────────────────────────────────",
        "",
        "/**",
        ` * Union of every valid static asset path from \"${dirLabel}\".`,
        " * Compile-time only - adds zero bytes to the production bundle.",
        " */",
        `export type ${typeName} =`,
        `${pathUnion};`,
        "",
        "/**",
        " * Validate and return a static asset path.",
        " *",
        " * Identity function at runtime - any bundler will inline it",
        " * to a bare string literal. Zero overhead.",
        " */",
        `export function ${fnName}<T extends ${typeName}>(path: T): T {`,
        "  return path;",
        "}",
        "",
    ].join("\n");
}

function writeIfChanged(entry: ResolvedDir, content: string): boolean {
    const hash = createHash("md5").update(content).digest("hex");
    if (hash === entry.lastHash) return false;

    mkdirSync(dirname(entry.outFile), { recursive: true });
    writeFileSync(entry.outFile, content, "utf-8");
    entry.lastHash = hash;
    return true;
}

export function createGenerator(
    options: StaticAssetsOptions = {},
    runtime: GeneratorRuntimeOptions,
): StaticAssetsGenerator {
    const {
        dirs = ["public"],
        outDir = "src/generated",
        extensions = [],
        exclude = [],
        fnName = "asset",
        typeName = "AssetPath",
    } = options;

    const resolvedDirs = normalizeDirs(dirs, runtime.root, outDir);

    for (const entry of resolvedDirs) {
        if (existsSync(entry.outFile)) {
            const existing = readFileSync(entry.outFile, "utf-8");
            entry.lastHash = createHash("md5").update(existing).digest("hex");
        }
    }

    const pathsCache = new Map<string, string>();

    const generateForDir = (entry: ResolvedDir): boolean => {
        const paths = collectPaths(entry.absPath, entry.absPath, entry.prefix, extensions, exclude);
        const cacheKey = paths.join("\n");

        if (pathsCache.get(entry.absPath) === cacheKey) {
            return false;
        }

        const content = generateModule(paths, entry.relPath, typeName, fnName);
        const changed = writeIfChanged(entry, content);
        pathsCache.set(entry.absPath, cacheKey);
        return changed;
    };

    return {
        generateAll(): string[] {
            const changed: string[] = [];

            for (const entry of resolvedDirs) {
                if (generateForDir(entry)) {
                    changed.push(entry.outRelative);
                }
            }

            return changed;
        },

        generateForPath(filePath: string): string | undefined {
            const normalizedPath = resolve(filePath);
            const entry = resolvedDirs.find((dir) => normalizedPath.startsWith(dir.absPath));

            if (!entry) return undefined;
            return generateForDir(entry) ? entry.outRelative : undefined;
        },

        getWatchedPaths(): string[] {
            return resolvedDirs.map((entry) => entry.absPath);
        },
    };
}
